DROP MATERIALIZED VIEW IF EXISTS yj_eigen_sec  CASCADE;
CREATE MATERIALIZED VIEW yj_eigen_sec AS
  WITH pvt AS (
    --筛选实验室指标，分别提取入ICU后24小时的最大值、最小值、平均值
         SELECT yc.subject_id,
            yc.hadm_id,
            yc.icustay_id,
            yc.intime,
            yc.icu_length_of_stay,
            yc.classlabel,
            yc.age,
                CASE
                    WHEN (le.itemid = 50821) THEN 'pO2'::text
                    WHEN (le.itemid = 50818) THEN 'pCO2'::text
                    WHEN (le.itemid = 50820) THEN 'pH'::text
                    WHEN (le.itemid = 50822) THEN 'POTASSIUM'::text
                    WHEN (le.itemid = 50808) THEN 'CALCIUM'::text
                    WHEN (le.itemid = 50824) THEN 'SODIUM'::text
                    WHEN (le.itemid = 50806) THEN 'CHLORIDE'::text
                    WHEN (le.itemid = 50809) THEN 'GLUCOSE'::text
                    WHEN (le.itemid = 50803) THEN 'BICARBONATE'::text
                    WHEN (le.itemid = 50804) THEN 'BICARBONATE'::text
                    WHEN (le.itemid = 50802) THEN 'BE'::text
                    WHEN (le.itemid = 51300) THEN 'WBC'::text
                    WHEN (le.itemid = 51301) THEN 'WBC'::text
                    WHEN (le.itemid = 51279) THEN 'RBC'::text
                    WHEN (le.itemid = 51265) THEN 'PLATELET'::text
                    WHEN (le.itemid = 50889) THEN 'CRP'::text
                    WHEN (le.itemid = 50813) THEN 'LACTATE'::text
                    WHEN (le.itemid = 50861) THEN 'ALT'::text
                    WHEN (le.itemid = 50878) THEN 'AST'::text
                    WHEN (le.itemid = 50912) THEN 'CREATININE'::text
                    WHEN (le.itemid = 51006) THEN 'BUN'::text
                    WHEN (le.itemid = 50867) THEN 'AMYLASE'::text
                    WHEN (le.itemid = 50956) THEN 'LIPASE'::text
                    WHEN (le.itemid = 51274) THEN 'PT'::text
                    WHEN (le.itemid = 51237) THEN 'INR'::text
                    WHEN (le.itemid = 51196) THEN 'D-Dimer'::text
                    WHEN (le.itemid = 51214) THEN 'FIB'::text
                    WHEN (le.itemid = 51275) THEN 'PTT'::text
                    WHEN (le.itemid = 51498) THEN 'SG'::text
                    WHEN (le.itemid = 51084) THEN 'GLU-UC'::text
                    WHEN (le.itemid = 51466) THEN 'Blood-UR'::text
                    WHEN (le.itemid = 51094) THEN 'PH-UC'::text
                    WHEN (le.itemid = 51491) THEN 'PH-UH'::text
                    WHEN (le.itemid = 51102) THEN 'PRO-UC'::text
                    WHEN (le.itemid = 51492) THEN 'PRO-UH'::text
                    WHEN (le.itemid = 51487) THEN 'NIT-UH'::text
                    WHEN (le.itemid = 51484) THEN 'KET-UH'::text
                    WHEN (le.itemid = 51486) THEN 'LEU-UH'::text
                    WHEN (le.itemid = 51514) THEN 'UBG-UH'::text
                    ELSE NULL::text
                END AS label,
                CASE
                    WHEN ((le.itemid = 50803) AND (le.valuenum > (10000)::double precision)) THEN NULL::double precision
                    WHEN ((le.itemid = 50804) AND (le.valuenum > (10000)::double precision)) THEN NULL::double precision
                    WHEN ((le.itemid = 50806) AND (le.valuenum > (10000)::double precision)) THEN NULL::double precision
                    WHEN ((le.itemid = 50912) AND (le.valuenum > (150)::double precision)) THEN NULL::double precision
                    WHEN ((le.itemid = 50809) AND (le.valuenum > (10000)::double precision)) THEN NULL::double precision
                    WHEN ((le.itemid = 50813) AND (le.valuenum > (50)::double precision)) THEN NULL::double precision
                    WHEN ((le.itemid = 51265) AND (le.valuenum > (10000)::double precision)) THEN NULL::double precision
                    WHEN ((le.itemid = 50822) AND (le.valuenum > (30)::double precision)) THEN NULL::double precision
                    WHEN ((le.itemid = 51275) AND (le.valuenum > (150)::double precision)) THEN NULL::double precision
                    WHEN ((le.itemid = 51237) AND (le.valuenum > (50)::double precision)) THEN NULL::double precision
                    WHEN ((le.itemid = 51274) AND (le.valuenum > (150)::double precision)) THEN NULL::double precision
                    WHEN ((le.itemid = 50824) AND (le.valuenum > (200)::double precision)) THEN NULL::double precision
                    WHEN ((le.itemid = 51006) AND (le.valuenum > (300)::double precision)) THEN NULL::double precision
                    WHEN ((le.itemid = 51300) AND (le.valuenum > (1000)::double precision)) THEN NULL::double precision
                    WHEN ((le.itemid = 51301) AND (le.valuenum > (1000)::double precision)) THEN NULL::double precision
                    ELSE le.valuenum
                END AS valuenum
           FROM (mimiciii.yj_cohort_sec yc
             LEFT JOIN mimiciii.labevents le ON (((yc.subject_id = le.subject_id) AND (yc.hadm_id = le.hadm_id) AND ((le.charttime >= (yc.intime - '06:00:00'::interval hour)) AND (le.charttime <= (yc.intime + '1 day'::interval day))) AND (le.itemid = ANY (ARRAY[50821, 50818, 50820, 50822, 50808, 50824, 50806, 50809, 50803, 50804, 50802, 51300, 51301, 51279, 51265, 50889, 50813, 50861, 50878, 50912, 51006, 50867, 50956, 51274, 51237, 51196, 51214, 51275, 51498, 51084, 51466, 51094, 51491, 51102, 51492, 51487, 51484, 51486, 51514])) AND (le.valuenum IS NOT NULL) AND (le.valuenum > (0)::double precision))))
        ), labval AS (
    --计算实验室指标的最大值、最小值、平均值
         SELECT pvt.subject_id,
            pvt.hadm_id,
            pvt.icu_length_of_stay,
            pvt.icustay_id,
            pvt.intime,
            pvt.age,
            pvt.classlabel,
            min(
                CASE
                    WHEN (pvt.label = 'pO2'::text) THEN pvt.valuenum
                    ELSE NULL::double precision
                END) AS po2_min,
            max(
                CASE
                    WHEN (pvt.label = 'pO2'::text) THEN pvt.valuenum
                    ELSE NULL::double precision
                END) AS po2_max,
            avg(
                CASE
                    WHEN (pvt.label = 'pO2'::text) THEN pvt.valuenum
                    ELSE NULL::double precision
                END) AS po2_avg,
            min(
                CASE
                    WHEN (pvt.label = 'pCO2'::text) THEN pvt.valuenum
                    ELSE NULL::double precision
                END) AS pco2_min,
            max(
                CASE
                    WHEN (pvt.label = 'pCO2'::text) THEN pvt.valuenum
                    ELSE NULL::double precision
                END) AS pco2_max,
            avg(
                CASE
                    WHEN (pvt.label = 'pCO2'::text) THEN pvt.valuenum
                    ELSE NULL::double precision
                END) AS pco2_avg,
            min(
                CASE
                    WHEN (pvt.label = 'pH'::text) THEN pvt.valuenum
                    ELSE NULL::double precision
                END) AS ph_min,
            max(
                CASE
                    WHEN (pvt.label = 'pH'::text) THEN pvt.valuenum
                    ELSE NULL::double precision
                END) AS ph_max,
            avg(
                CASE
                    WHEN (pvt.label = 'pH'::text) THEN pvt.valuenum
                    ELSE NULL::double precision
                END) AS ph_avg,
            min(
                CASE
                    WHEN (pvt.label = 'POTASSIUM'::text) THEN pvt.valuenum
                    ELSE NULL::double precision
                END) AS potassium_min,
            max(
                CASE
                    WHEN (pvt.label = 'POTASSIUM'::text) THEN pvt.valuenum
                    ELSE NULL::double precision
                END) AS potassium_max,
            avg(
                CASE
                    WHEN (pvt.label = 'POTASSIUM'::text) THEN pvt.valuenum
                    ELSE NULL::double precision
                END) AS potassium_avg,
            min(
                CASE
                    WHEN (pvt.label = 'CALCIUM'::text) THEN pvt.valuenum
                    ELSE NULL::double precision
                END) AS calcium_min,
            max(
                CASE
                    WHEN (pvt.label = 'CALCIUM'::text) THEN pvt.valuenum
                    ELSE NULL::double precision
                END) AS calcium_max,
            avg(
                CASE
                    WHEN (pvt.label = 'CALCIUM'::text) THEN pvt.valuenum
                    ELSE NULL::double precision
                END) AS calcium_avg,
            min(
                CASE
                    WHEN (pvt.label = 'SODIUM'::text) THEN pvt.valuenum
                    ELSE NULL::double precision
                END) AS sodium_min,
            max(
                CASE
                    WHEN (pvt.label = 'SODIUM'::text) THEN pvt.valuenum
                    ELSE NULL::double precision
                END) AS sodium_max,
            avg(
                CASE
                    WHEN (pvt.label = 'SODIUM'::text) THEN pvt.valuenum
                    ELSE NULL::double precision
                END) AS sodium_avg,
            min(
                CASE
                    WHEN (pvt.label = 'CHLORIDE'::text) THEN pvt.valuenum
                    ELSE NULL::double precision
                END) AS chloride_min,
            max(
                CASE
                    WHEN (pvt.label = 'CHLORIDE'::text) THEN pvt.valuenum
                    ELSE NULL::double precision
                END) AS chloride_max,
            avg(
                CASE
                    WHEN (pvt.label = 'CHLORIDE'::text) THEN pvt.valuenum
                    ELSE NULL::double precision
                END) AS chloride_avg,
            min(
                CASE
                    WHEN (pvt.label = 'GLUCOSE'::text) THEN pvt.valuenum
                    ELSE NULL::double precision
                END) AS glucose_min,
            max(
                CASE
                    WHEN (pvt.label = 'GLUCOSE'::text) THEN pvt.valuenum
                    ELSE NULL::double precision
                END) AS glucose_max,
            avg(
                CASE
                    WHEN (pvt.label = 'GLUCOSE'::text) THEN pvt.valuenum
                    ELSE NULL::double precision
                END) AS glucose_avg,
            min(
                CASE
                    WHEN (pvt.label = 'BICARBONATE'::text) THEN pvt.valuenum
                    ELSE NULL::double precision
                END) AS bicarbonate_min,
            max(
                CASE
                    WHEN (pvt.label = 'BICARBONATE'::text) THEN pvt.valuenum
                    ELSE NULL::double precision
                END) AS bicarbonate_max,
            avg(
                CASE
                    WHEN (pvt.label = 'BICARBONATE'::text) THEN pvt.valuenum
                    ELSE NULL::double precision
                END) AS bicarbonate_avg,
            min(
                CASE
                    WHEN (pvt.label = 'BE'::text) THEN pvt.valuenum
                    ELSE NULL::double precision
                END) AS be_min,
            max(
                CASE
                    WHEN (pvt.label = 'BE'::text) THEN pvt.valuenum
                    ELSE NULL::double precision
                END) AS be_max,
            avg(
                CASE
                    WHEN (pvt.label = 'BE'::text) THEN pvt.valuenum
                    ELSE NULL::double precision
                END) AS be_avg,
            min(
                CASE
                    WHEN (pvt.label = 'WBC'::text) THEN pvt.valuenum
                    ELSE NULL::double precision
                END) AS wbc_min,
            max(
                CASE
                    WHEN (pvt.label = 'WBC'::text) THEN pvt.valuenum
                    ELSE NULL::double precision
                END) AS wbc_max,
            avg(
                CASE
                    WHEN (pvt.label = 'WBC'::text) THEN pvt.valuenum
                    ELSE NULL::double precision
                END) AS wbc_avg,
            min(
                CASE
                    WHEN (pvt.label = 'RBC'::text) THEN pvt.valuenum
                    ELSE NULL::double precision
                END) AS rbc_min,
            max(
                CASE
                    WHEN (pvt.label = 'RBC'::text) THEN pvt.valuenum
                    ELSE NULL::double precision
                END) AS rbc_max,
            avg(
                CASE
                    WHEN (pvt.label = 'RBC'::text) THEN pvt.valuenum
                    ELSE NULL::double precision
                END) AS rbc_avg,
            min(
                CASE
                    WHEN (pvt.label = 'PLATELET'::text) THEN pvt.valuenum
                    ELSE NULL::double precision
                END) AS platelet_min,
            max(
                CASE
                    WHEN (pvt.label = 'PLATELET'::text) THEN pvt.valuenum
                    ELSE NULL::double precision
                END) AS platelet_max,
            avg(
                CASE
                    WHEN (pvt.label = 'PLATELET'::text) THEN pvt.valuenum
                    ELSE NULL::double precision
                END) AS platelet_avg,
            min(
                CASE
                    WHEN (pvt.label = 'CRP'::text) THEN pvt.valuenum
                    ELSE NULL::double precision
                END) AS crp_min,
            max(
                CASE
                    WHEN (pvt.label = 'CRP'::text) THEN pvt.valuenum
                    ELSE NULL::double precision
                END) AS crp_max,
            avg(
                CASE
                    WHEN (pvt.label = 'CRP'::text) THEN pvt.valuenum
                    ELSE NULL::double precision
                END) AS crp_avg,
            min(
                CASE
                    WHEN (pvt.label = 'LACTATE'::text) THEN pvt.valuenum
                    ELSE NULL::double precision
                END) AS lactate_min,
            max(
                CASE
                    WHEN (pvt.label = 'LACTATE'::text) THEN pvt.valuenum
                    ELSE NULL::double precision
                END) AS lactate_max,
            avg(
                CASE
                    WHEN (pvt.label = 'LACTATE'::text) THEN pvt.valuenum
                    ELSE NULL::double precision
                END) AS lactate_avg,
            min(
                CASE
                    WHEN (pvt.label = 'ALT'::text) THEN pvt.valuenum
                    ELSE NULL::double precision
                END) AS alt_min,
            max(
                CASE
                    WHEN (pvt.label = 'ALT'::text) THEN pvt.valuenum
                    ELSE NULL::double precision
                END) AS alt_max,
            avg(
                CASE
                    WHEN (pvt.label = 'ALT'::text) THEN pvt.valuenum
                    ELSE NULL::double precision
                END) AS alt_avg,
            min(
                CASE
                    WHEN (pvt.label = 'AST'::text) THEN pvt.valuenum
                    ELSE NULL::double precision
                END) AS ast_min,
            max(
                CASE
                    WHEN (pvt.label = 'AST'::text) THEN pvt.valuenum
                    ELSE NULL::double precision
                END) AS ast_max,
            avg(
                CASE
                    WHEN (pvt.label = 'AST'::text) THEN pvt.valuenum
                    ELSE NULL::double precision
                END) AS ast_avg,
            min(
                CASE
                    WHEN (pvt.label = 'CREATININE'::text) THEN pvt.valuenum
                    ELSE NULL::double precision
                END) AS creatinine_min,
            max(
                CASE
                    WHEN (pvt.label = 'CREATININE'::text) THEN pvt.valuenum
                    ELSE NULL::double precision
                END) AS creatinine_max,
            avg(
                CASE
                    WHEN (pvt.label = 'CREATININE'::text) THEN pvt.valuenum
                    ELSE NULL::double precision
                END) AS creatinine_avg,
            min(
                CASE
                    WHEN (pvt.label = 'BUN'::text) THEN pvt.valuenum
                    ELSE NULL::double precision
                END) AS bun_min,
            max(
                CASE
                    WHEN (pvt.label = 'BUN'::text) THEN pvt.valuenum
                    ELSE NULL::double precision
                END) AS bun_max,
            avg(
                CASE
                    WHEN (pvt.label = 'BUN'::text) THEN pvt.valuenum
                    ELSE NULL::double precision
                END) AS bun_avg,
            min(
                CASE
                    WHEN (pvt.label = 'AMYLASE'::text) THEN pvt.valuenum
                    ELSE NULL::double precision
                END) AS amylase_min,
            max(
                CASE
                    WHEN (pvt.label = 'AMYLASE'::text) THEN pvt.valuenum
                    ELSE NULL::double precision
                END) AS amylase_max,
            avg(
                CASE
                    WHEN (pvt.label = 'AMYLASE'::text) THEN pvt.valuenum
                    ELSE NULL::double precision
                END) AS amylase_avg,
            min(
                CASE
                    WHEN (pvt.label = 'LIPASE'::text) THEN pvt.valuenum
                    ELSE NULL::double precision
                END) AS lipase_min,
            max(
                CASE
                    WHEN (pvt.label = 'LIPASE'::text) THEN pvt.valuenum
                    ELSE NULL::double precision
                END) AS lipase_max,
            avg(
                CASE
                    WHEN (pvt.label = 'LIPASE'::text) THEN pvt.valuenum
                    ELSE NULL::double precision
                END) AS lipase_avg,
            min(
                CASE
                    WHEN (pvt.label = 'PT'::text) THEN pvt.valuenum
                    ELSE NULL::double precision
                END) AS pt_min,
            max(
                CASE
                    WHEN (pvt.label = 'PT'::text) THEN pvt.valuenum
                    ELSE NULL::double precision
                END) AS pt_max,
            avg(
                CASE
                    WHEN (pvt.label = 'PT'::text) THEN pvt.valuenum
                    ELSE NULL::double precision
                END) AS pt_avg,
            min(
                CASE
                    WHEN (pvt.label = 'INR'::text) THEN pvt.valuenum
                    ELSE NULL::double precision
                END) AS inr_min,
            max(
                CASE
                    WHEN (pvt.label = 'INR'::text) THEN pvt.valuenum
                    ELSE NULL::double precision
                END) AS inr_max,
            avg(
                CASE
                    WHEN (pvt.label = 'INR'::text) THEN pvt.valuenum
                    ELSE NULL::double precision
                END) AS inr_avg,
            min(
                CASE
                    WHEN (pvt.label = 'D-Dimer'::text) THEN pvt.valuenum
                    ELSE NULL::double precision
                END) AS ddimer_min,
            max(
                CASE
                    WHEN (pvt.label = 'D-Dimer'::text) THEN pvt.valuenum
                    ELSE NULL::double precision
                END) AS ddimer_max,
            avg(
                CASE
                    WHEN (pvt.label = 'D-Dimer'::text) THEN pvt.valuenum
                    ELSE NULL::double precision
                END) AS ddimer_avg,
            min(
                CASE
                    WHEN (pvt.label = 'FIB'::text) THEN pvt.valuenum
                    ELSE NULL::double precision
                END) AS fib_min,
            max(
                CASE
                    WHEN (pvt.label = 'FIB'::text) THEN pvt.valuenum
                    ELSE NULL::double precision
                END) AS fib_max,
            avg(
                CASE
                    WHEN (pvt.label = 'FIB'::text) THEN pvt.valuenum
                    ELSE NULL::double precision
                END) AS fib_avg,
            min(
                CASE
                    WHEN (pvt.label = 'PTT'::text) THEN pvt.valuenum
                    ELSE NULL::double precision
                END) AS ptt_min,
            max(
                CASE
                    WHEN (pvt.label = 'PTT'::text) THEN pvt.valuenum
                    ELSE NULL::double precision
                END) AS ptt_max,
            avg(
                CASE
                    WHEN (pvt.label = 'PTT'::text) THEN pvt.valuenum
                    ELSE NULL::double precision
                END) AS ptt_avg,
            min(
                CASE
                    WHEN (pvt.label = 'SG'::text) THEN pvt.valuenum
                    ELSE NULL::double precision
                END) AS sg_min,
            max(
                CASE
                    WHEN (pvt.label = 'SG'::text) THEN pvt.valuenum
                    ELSE NULL::double precision
                END) AS sg_max,
            avg(
                CASE
                    WHEN (pvt.label = 'SG'::text) THEN pvt.valuenum
                    ELSE NULL::double precision
                END) AS sg_avg,
            min(
                CASE
                    WHEN (pvt.label = 'GLU-UC'::text) THEN pvt.valuenum
                    ELSE NULL::double precision
                END) AS gluuc_min,
            max(
                CASE
                    WHEN (pvt.label = 'GLU-UC'::text) THEN pvt.valuenum
                    ELSE NULL::double precision
                END) AS gluuc_max,
            avg(
                CASE
                    WHEN (pvt.label = 'GLU-UC'::text) THEN pvt.valuenum
                    ELSE NULL::double precision
                END) AS gluuc_avg,
            min(
                CASE
                    WHEN (pvt.label = 'Blood-UR'::text) THEN pvt.valuenum
                    ELSE NULL::double precision
                END) AS bloodu_min,
            max(
                CASE
                    WHEN (pvt.label = 'Blood-UR'::text) THEN pvt.valuenum
                    ELSE NULL::double precision
                END) AS bloodu_max,
            avg(
                CASE
                    WHEN (pvt.label = 'Blood-UR'::text) THEN pvt.valuenum
                    ELSE NULL::double precision
                END) AS bloodu_avg,
            min(
                CASE
                    WHEN (pvt.label = 'PH-UC'::text) THEN pvt.valuenum
                    ELSE NULL::double precision
                END) AS phuc_min,
            max(
                CASE
                    WHEN (pvt.label = 'PH-UC'::text) THEN pvt.valuenum
                    ELSE NULL::double precision
                END) AS phuc_max,
            avg(
                CASE
                    WHEN (pvt.label = 'PH-UC'::text) THEN pvt.valuenum
                    ELSE NULL::double precision
                END) AS phuc_avg,
            min(
                CASE
                    WHEN (pvt.label = 'PH-UH'::text) THEN pvt.valuenum
                    ELSE NULL::double precision
                END) AS phuh_min,
            max(
                CASE
                    WHEN (pvt.label = 'PH-UH'::text) THEN pvt.valuenum
                    ELSE NULL::double precision
                END) AS phuh_max,
            avg(
                CASE
                    WHEN (pvt.label = 'PH-UH'::text) THEN pvt.valuenum
                    ELSE NULL::double precision
                END) AS phuh_avg,
            min(
                CASE
                    WHEN (pvt.label = 'PRO-UC'::text) THEN pvt.valuenum
                    ELSE NULL::double precision
                END) AS prouc_min,
            max(
                CASE
                    WHEN (pvt.label = 'PRO-UC'::text) THEN pvt.valuenum
                    ELSE NULL::double precision
                END) AS prouc_max,
            avg(
                CASE
                    WHEN (pvt.label = 'PRO-UC'::text) THEN pvt.valuenum
                    ELSE NULL::double precision
                END) AS prouc_avg,
            min(
                CASE
                    WHEN (pvt.label = 'PRO-UH'::text) THEN pvt.valuenum
                    ELSE NULL::double precision
                END) AS prouh_min,
            max(
                CASE
                    WHEN (pvt.label = 'PRO-UH'::text) THEN pvt.valuenum
                    ELSE NULL::double precision
                END) AS prouh_max,
            avg(
                CASE
                    WHEN (pvt.label = 'PRO-UH'::text) THEN pvt.valuenum
                    ELSE NULL::double precision
                END) AS prouh_avg,
            min(
                CASE
                    WHEN (pvt.label = 'NIT-UH'::text) THEN pvt.valuenum
                    ELSE NULL::double precision
                END) AS nit_min,
            max(
                CASE
                    WHEN (pvt.label = 'NIT-UH'::text) THEN pvt.valuenum
                    ELSE NULL::double precision
                END) AS nit_max,
            avg(
                CASE
                    WHEN (pvt.label = 'NIT-UH'::text) THEN pvt.valuenum
                    ELSE NULL::double precision
                END) AS nit_avg,
            min(
                CASE
                    WHEN (pvt.label = 'KET-UH'::text) THEN pvt.valuenum
                    ELSE NULL::double precision
                END) AS ket_min,
            max(
                CASE
                    WHEN (pvt.label = 'KET-UH'::text) THEN pvt.valuenum
                    ELSE NULL::double precision
                END) AS ket_max,
            avg(
                CASE
                    WHEN (pvt.label = 'KET-UH'::text) THEN pvt.valuenum
                    ELSE NULL::double precision
                END) AS ket_avg,
            min(
                CASE
                    WHEN (pvt.label = 'LEU-UH'::text) THEN pvt.valuenum
                    ELSE NULL::double precision
                END) AS leu_min,
            max(
                CASE
                    WHEN (pvt.label = 'LEU-UH'::text) THEN pvt.valuenum
                    ELSE NULL::double precision
                END) AS leu_max,
            avg(
                CASE
                    WHEN (pvt.label = 'LEU-UH'::text) THEN pvt.valuenum
                    ELSE NULL::double precision
                END) AS leu_avg,
            min(
                CASE
                    WHEN (pvt.label = 'UBG-UH'::text) THEN pvt.valuenum
                    ELSE NULL::double precision
                END) AS ubg_min,
            max(
                CASE
                    WHEN (pvt.label = 'UBG-UH'::text) THEN pvt.valuenum
                    ELSE NULL::double precision
                END) AS ubg_max,
            avg(
                CASE
                    WHEN (pvt.label = 'UBG-UH'::text) THEN pvt.valuenum
                    ELSE NULL::double precision
                END) AS ubg_avg
           FROM pvt
          GROUP BY pvt.subject_id, pvt.hadm_id, pvt.icustay_id, pvt.icu_length_of_stay, pvt.intime, pvt.age, pvt.classlabel
        ), addvital AS (
    --加入关键生理参数，从vitalfirstday视图中提取的
         SELECT lab.subject_id,
            lab.hadm_id,
            lab.icu_length_of_stay,
            lab.icustay_id,
            lab.intime,
            lab.age,
            lab.classlabel,
            lab.po2_min,
            lab.po2_max,
            lab.po2_avg,
            lab.pco2_min,
            lab.pco2_max,
            lab.pco2_avg,
            lab.ph_min,
            lab.ph_max,
            lab.ph_avg,
            lab.potassium_min,
            lab.potassium_max,
            lab.potassium_avg,
            lab.calcium_min,
            lab.calcium_max,
            lab.calcium_avg,
            lab.sodium_min,
            lab.sodium_max,
            lab.sodium_avg,
            lab.chloride_min,
            lab.chloride_max,
            lab.chloride_avg,
            lab.glucose_min,
            lab.glucose_max,
            lab.glucose_avg,
            lab.bicarbonate_min,
            lab.bicarbonate_max,
            lab.bicarbonate_avg,
            lab.be_min,
            lab.be_max,
            lab.be_avg,
            lab.wbc_min,
            lab.wbc_max,
            lab.wbc_avg,
            lab.rbc_min,
            lab.rbc_max,
            lab.rbc_avg,
            lab.platelet_min,
            lab.platelet_max,
            lab.platelet_avg,
            lab.crp_min,
            lab.crp_max,
            lab.crp_avg,
            lab.lactate_min,
            lab.lactate_max,
            lab.lactate_avg,
            lab.alt_min,
            lab.alt_max,
            lab.alt_avg,
            lab.ast_min,
            lab.ast_max,
            lab.ast_avg,
            lab.creatinine_min,
            lab.creatinine_max,
            lab.creatinine_avg,
            lab.bun_min,
            lab.bun_max,
            lab.bun_avg,
            lab.amylase_min,
            lab.amylase_max,
            lab.amylase_avg,
            lab.lipase_min,
            lab.lipase_max,
            lab.lipase_avg,
            lab.pt_min,
            lab.pt_max,
            lab.pt_avg,
            lab.inr_min,
            lab.inr_max,
            lab.inr_avg,
            lab.ddimer_min,
            lab.ddimer_max,
            lab.ddimer_avg,
            lab.fib_min,
            lab.fib_max,
            lab.fib_avg,
            lab.ptt_min,
            lab.ptt_max,
            lab.ptt_avg,
            lab.sg_min,
            lab.sg_max,
            lab.sg_avg,
            lab.gluuc_min,
            lab.gluuc_max,
            lab.gluuc_avg,
            lab.bloodu_min,
            lab.bloodu_max,
            lab.bloodu_avg,
            lab.phuc_min,
            lab.phuc_max,
            lab.phuc_avg,
            lab.phuh_min,
            lab.phuh_max,
            lab.phuh_avg,
            lab.prouc_min,
            lab.prouc_max,
            lab.prouc_avg,
            lab.prouh_min,
            lab.prouh_max,
            lab.prouh_avg,
            lab.nit_min,
            lab.nit_max,
            lab.nit_avg,
            lab.ket_min,
            lab.ket_max,
            lab.ket_avg,
            lab.leu_min,
            lab.leu_max,
            lab.leu_avg,
            lab.ubg_min,
            lab.ubg_max,
            lab.ubg_avg,
            vf.heartrate_max,
            vf.heartrate_mean,
            vf.heartrate_min,
            vf.sysbp_max,
            vf.sysbp_mean,
            vf.sysbp_min,
            vf.diasbp_max,
            vf.diasbp_mean,
            vf.diasbp_min,
            vf.meanbp_max,
            vf.meanbp_mean,
            vf.meanbp_min,
            vf.resprate_max,
            vf.resprate_mean,
            vf.resprate_min,
            vf.spo2_max,
            vf.spo2_mean,
            vf.spo2_min
           FROM (labval lab
             LEFT JOIN mimiciii.vitalsfirstday vf ON (((vf.subject_id = lab.subject_id) AND (vf.hadm_id = lab.hadm_id) AND (vf.icustay_id = lab.icustay_id))))
        ), adduosi AS (
    --从uofirstday视图中提取病人入ICU后24小时的尿量
    --此外还试图根据心率和收缩压来计算休克指数SI的值，但这个值是一个实时量，不能这样算，因此该指标无效，需进一步研究提取
         SELECT av.subject_id,
            av.hadm_id,
            av.icu_length_of_stay,
            av.icustay_id,
            av.intime,
            av.age,
            av.classlabel,
            av.po2_min,
            av.po2_max,
            av.po2_avg,
            av.pco2_min,
            av.pco2_max,
            av.pco2_avg,
            av.ph_min,
            av.ph_max,
            av.ph_avg,
            av.potassium_min,
            av.potassium_max,
            av.potassium_avg,
            av.calcium_min,
            av.calcium_max,
            av.calcium_avg,
            av.sodium_min,
            av.sodium_max,
            av.sodium_avg,
            av.chloride_min,
            av.chloride_max,
            av.chloride_avg,
            av.glucose_min,
            av.glucose_max,
            av.glucose_avg,
            av.bicarbonate_min,
            av.bicarbonate_max,
            av.bicarbonate_avg,
            av.be_min,
            av.be_max,
            av.be_avg,
            av.wbc_min,
            av.wbc_max,
            av.wbc_avg,
            av.rbc_min,
            av.rbc_max,
            av.rbc_avg,
            av.platelet_min,
            av.platelet_max,
            av.platelet_avg,
            av.crp_min,
            av.crp_max,
            av.crp_avg,
            av.lactate_min,
            av.lactate_max,
            av.lactate_avg,
            av.alt_min,
            av.alt_max,
            av.alt_avg,
            av.ast_min,
            av.ast_max,
            av.ast_avg,
            av.creatinine_min,
            av.creatinine_max,
            av.creatinine_avg,
            av.bun_min,
            av.bun_max,
            av.bun_avg,
            av.amylase_min,
            av.amylase_max,
            av.amylase_avg,
            av.lipase_min,
            av.lipase_max,
            av.lipase_avg,
            av.pt_min,
            av.pt_max,
            av.pt_avg,
            av.inr_min,
            av.inr_max,
            av.inr_avg,
            av.ddimer_min,
            av.ddimer_max,
            av.ddimer_avg,
            av.fib_min,
            av.fib_max,
            av.fib_avg,
            av.ptt_min,
            av.ptt_max,
            av.ptt_avg,
            av.sg_min,
            av.sg_max,
            av.sg_avg,
            av.gluuc_min,
            av.gluuc_max,
            av.gluuc_avg,
            av.bloodu_min,
            av.bloodu_max,
            av.bloodu_avg,
            av.phuc_min,
            av.phuc_max,
            av.phuc_avg,
            av.phuh_min,
            av.phuh_max,
            av.phuh_avg,
            av.prouc_min,
            av.prouc_max,
            av.prouc_avg,
            av.prouh_min,
            av.prouh_max,
            av.prouh_avg,
            av.nit_min,
            av.nit_max,
            av.nit_avg,
            av.ket_min,
            av.ket_max,
            av.ket_avg,
            av.leu_min,
            av.leu_max,
            av.leu_avg,
            av.ubg_min,
            av.ubg_max,
            av.ubg_avg,
            av.heartrate_max,
            av.heartrate_mean,
            av.heartrate_min,
            av.sysbp_max,
            av.sysbp_mean,
            av.sysbp_min,
            av.diasbp_max,
            av.diasbp_mean,
            av.diasbp_min,
            av.meanbp_max,
            av.meanbp_mean,
            av.meanbp_min,
            av.resprate_max,
            av.resprate_mean,
            av.resprate_min,
            av.spo2_max,
            av.spo2_mean,
            av.spo2_min,
            uf.urineoutput,
            (av.heartrate_max / av.sysbp_max) AS si_max,
            (av.heartrate_mean / av.sysbp_mean) AS si_mean,
            (av.heartrate_min / av.sysbp_min) AS si_min
           FROM (addvital av
             LEFT JOIN mimiciii.uofirstday uf ON (((av.subject_id = uf.subject_id) AND (av.hadm_id = uf.hadm_id) AND (av.icustay_id = uf.icustay_id))))
        ), addgcs AS (
  --从表GCSfirstday中，提取入ICU后24小时的GCS
         SELECT aus.subject_id,
            aus.hadm_id,
            aus.icu_length_of_stay,
            aus.icustay_id,
            aus.intime,
            aus.age,
            aus.classlabel,
            aus.po2_min,
            aus.po2_max,
            aus.po2_avg,
            aus.pco2_min,
            aus.pco2_max,
            aus.pco2_avg,
            aus.ph_min,
            aus.ph_max,
            aus.ph_avg,
            aus.potassium_min,
            aus.potassium_max,
            aus.potassium_avg,
            aus.calcium_min,
            aus.calcium_max,
            aus.calcium_avg,
            aus.sodium_min,
            aus.sodium_max,
            aus.sodium_avg,
            aus.chloride_min,
            aus.chloride_max,
            aus.chloride_avg,
            aus.glucose_min,
            aus.glucose_max,
            aus.glucose_avg,
            aus.bicarbonate_min,
            aus.bicarbonate_max,
            aus.bicarbonate_avg,
            aus.be_min,
            aus.be_max,
            aus.be_avg,
            aus.wbc_min,
            aus.wbc_max,
            aus.wbc_avg,
            aus.rbc_min,
            aus.rbc_max,
            aus.rbc_avg,
            aus.platelet_min,
            aus.platelet_max,
            aus.platelet_avg,
            aus.crp_min,
            aus.crp_max,
            aus.crp_avg,
            aus.lactate_min,
            aus.lactate_max,
            aus.lactate_avg,
            aus.alt_min,
            aus.alt_max,
            aus.alt_avg,
            aus.ast_min,
            aus.ast_max,
            aus.ast_avg,
            aus.creatinine_min,
            aus.creatinine_max,
            aus.creatinine_avg,
            aus.bun_min,
            aus.bun_max,
            aus.bun_avg,
            aus.amylase_min,
            aus.amylase_max,
            aus.amylase_avg,
            aus.lipase_min,
            aus.lipase_max,
            aus.lipase_avg,
            aus.pt_min,
            aus.pt_max,
            aus.pt_avg,
            aus.inr_min,
            aus.inr_max,
            aus.inr_avg,
            aus.ddimer_min,
            aus.ddimer_max,
            aus.ddimer_avg,
            aus.fib_min,
            aus.fib_max,
            aus.fib_avg,
            aus.ptt_min,
            aus.ptt_max,
            aus.ptt_avg,
            aus.sg_min,
            aus.sg_max,
            aus.sg_avg,
            aus.gluuc_min,
            aus.gluuc_max,
            aus.gluuc_avg,
            aus.bloodu_min,
            aus.bloodu_max,
            aus.bloodu_avg,
            aus.phuc_min,
            aus.phuc_max,
            aus.phuc_avg,
            aus.phuh_min,
            aus.phuh_max,
            aus.phuh_avg,
            aus.prouc_min,
            aus.prouc_max,
            aus.prouc_avg,
            aus.prouh_min,
            aus.prouh_max,
            aus.prouh_avg,
            aus.nit_min,
            aus.nit_max,
            aus.nit_avg,
            aus.ket_min,
            aus.ket_max,
            aus.ket_avg,
            aus.leu_min,
            aus.leu_max,
            aus.leu_avg,
            aus.ubg_min,
            aus.ubg_max,
            aus.ubg_avg,
            aus.heartrate_max,
            aus.heartrate_mean,
            aus.heartrate_min,
            aus.sysbp_max,
            aus.sysbp_mean,
            aus.sysbp_min,
            aus.diasbp_max,
            aus.diasbp_mean,
            aus.diasbp_min,
            aus.meanbp_max,
            aus.meanbp_mean,
            aus.meanbp_min,
            aus.resprate_max,
            aus.resprate_mean,
            aus.resprate_min,
            aus.spo2_max,
            aus.spo2_mean,
            aus.spo2_min,
            aus.urineoutput,
            aus.si_max,
            aus.si_mean,
            aus.si_min,
            gf.mingcs
           FROM (adduosi aus
             LEFT JOIN mimiciii.gcsfirstday gf ON (((aus.subject_id = gf.subject_id) AND (aus.icustay_id = gf.icustay_id) AND (aus.hadm_id = gf.hadm_id))))
        ), addweight AS (
    --从weightfirstday中提取患者入ICU后24小时的体重
         SELECT ag.subject_id,
            ag.hadm_id,
            ag.icu_length_of_stay,
            ag.icustay_id,
            ag.intime,
            ag.age,
            ag.classlabel,
            ag.po2_min,
            ag.po2_max,
            ag.po2_avg,
            ag.pco2_min,
            ag.pco2_max,
            ag.pco2_avg,
            ag.ph_min,
            ag.ph_max,
            ag.ph_avg,
            ag.potassium_min,
            ag.potassium_max,
            ag.potassium_avg,
            ag.calcium_min,
            ag.calcium_max,
            ag.calcium_avg,
            ag.sodium_min,
            ag.sodium_max,
            ag.sodium_avg,
            ag.chloride_min,
            ag.chloride_max,
            ag.chloride_avg,
            ag.glucose_min,
            ag.glucose_max,
            ag.glucose_avg,
            ag.bicarbonate_min,
            ag.bicarbonate_max,
            ag.bicarbonate_avg,
            ag.be_min,
            ag.be_max,
            ag.be_avg,
            ag.wbc_min,
            ag.wbc_max,
            ag.wbc_avg,
            ag.rbc_min,
            ag.rbc_max,
            ag.rbc_avg,
            ag.platelet_min,
            ag.platelet_max,
            ag.platelet_avg,
            ag.crp_min,
            ag.crp_max,
            ag.crp_avg,
            ag.lactate_min,
            ag.lactate_max,
            ag.lactate_avg,
            ag.alt_min,
            ag.alt_max,
            ag.alt_avg,
            ag.ast_min,
            ag.ast_max,
            ag.ast_avg,
            ag.creatinine_min,
            ag.creatinine_max,
            ag.creatinine_avg,
            ag.bun_min,
            ag.bun_max,
            ag.bun_avg,
            ag.amylase_min,
            ag.amylase_max,
            ag.amylase_avg,
            ag.lipase_min,
            ag.lipase_max,
            ag.lipase_avg,
            ag.pt_min,
            ag.pt_max,
            ag.pt_avg,
            ag.inr_min,
            ag.inr_max,
            ag.inr_avg,
            ag.ddimer_min,
            ag.ddimer_max,
            ag.ddimer_avg,
            ag.fib_min,
            ag.fib_max,
            ag.fib_avg,
            ag.ptt_min,
            ag.ptt_max,
            ag.ptt_avg,
            ag.sg_min,
            ag.sg_max,
            ag.sg_avg,
            ag.gluuc_min,
            ag.gluuc_max,
            ag.gluuc_avg,
            ag.bloodu_min,
            ag.bloodu_max,
            ag.bloodu_avg,
            ag.phuc_min,
            ag.phuc_max,
            ag.phuc_avg,
            ag.phuh_min,
            ag.phuh_max,
            ag.phuh_avg,
            ag.prouc_min,
            ag.prouc_max,
            ag.prouc_avg,
            ag.prouh_min,
            ag.prouh_max,
            ag.prouh_avg,
            ag.nit_min,
            ag.nit_max,
            ag.nit_avg,
            ag.ket_min,
            ag.ket_max,
            ag.ket_avg,
            ag.leu_min,
            ag.leu_max,
            ag.leu_avg,
            ag.ubg_min,
            ag.ubg_max,
            ag.ubg_avg,
            ag.heartrate_max,
            ag.heartrate_mean,
            ag.heartrate_min,
            ag.sysbp_max,
            ag.sysbp_mean,
            ag.sysbp_min,
            ag.diasbp_max,
            ag.diasbp_mean,
            ag.diasbp_min,
            ag.meanbp_max,
            ag.meanbp_mean,
            ag.meanbp_min,
            ag.resprate_max,
            ag.resprate_mean,
            ag.resprate_min,
            ag.spo2_max,
            ag.spo2_mean,
            ag.spo2_min,
            ag.urineoutput,
            ag.si_max,
            ag.si_mean,
            ag.si_min,
            ag.mingcs,
            wf.weight
           FROM (addgcs ag
             LEFT JOIN mimiciii.weightfirstday wf ON ((ag.icustay_id = wf.icustay_id)))
        ), addheight AS (
    --从heightfirstday视图中查找患者入ICU后24小时的身高指标
    --身高有height、height_chart、height_echo三个记录，以第一个为主，如果第一个缺失，用后面的两个代替
         SELECT aw.subject_id,
            aw.hadm_id,
            aw.icu_length_of_stay,
            aw.icustay_id,
            aw.intime,
            aw.age,
            aw.classlabel,
            aw.po2_min,
            aw.po2_max,
            aw.po2_avg,
            aw.pco2_min,
            aw.pco2_max,
            aw.pco2_avg,
            aw.ph_min,
            aw.ph_max,
            aw.ph_avg,
            aw.potassium_min,
            aw.potassium_max,
            aw.potassium_avg,
            aw.calcium_min,
            aw.calcium_max,
            aw.calcium_avg,
            aw.sodium_min,
            aw.sodium_max,
            aw.sodium_avg,
            aw.chloride_min,
            aw.chloride_max,
            aw.chloride_avg,
            aw.glucose_min,
            aw.glucose_max,
            aw.glucose_avg,
            aw.bicarbonate_min,
            aw.bicarbonate_max,
            aw.bicarbonate_avg,
            aw.be_min,
            aw.be_max,
            aw.be_avg,
            aw.wbc_min,
            aw.wbc_max,
            aw.wbc_avg,
            aw.rbc_min,
            aw.rbc_max,
            aw.rbc_avg,
            aw.platelet_min,
            aw.platelet_max,
            aw.platelet_avg,
            aw.crp_min,
            aw.crp_max,
            aw.crp_avg,
            aw.lactate_min,
            aw.lactate_max,
            aw.lactate_avg,
            aw.alt_min,
            aw.alt_max,
            aw.alt_avg,
            aw.ast_min,
            aw.ast_max,
            aw.ast_avg,
            aw.creatinine_min,
            aw.creatinine_max,
            aw.creatinine_avg,
            aw.bun_min,
            aw.bun_max,
            aw.bun_avg,
            aw.amylase_min,
            aw.amylase_max,
            aw.amylase_avg,
            aw.lipase_min,
            aw.lipase_max,
            aw.lipase_avg,
            aw.pt_min,
            aw.pt_max,
            aw.pt_avg,
            aw.inr_min,
            aw.inr_max,
            aw.inr_avg,
            aw.ddimer_min,
            aw.ddimer_max,
            aw.ddimer_avg,
            aw.fib_min,
            aw.fib_max,
            aw.fib_avg,
            aw.ptt_min,
            aw.ptt_max,
            aw.ptt_avg,
            aw.sg_min,
            aw.sg_max,
            aw.sg_avg,
            aw.gluuc_min,
            aw.gluuc_max,
            aw.gluuc_avg,
            aw.bloodu_min,
            aw.bloodu_max,
            aw.bloodu_avg,
            aw.phuc_min,
            aw.phuc_max,
            aw.phuc_avg,
            aw.phuh_min,
            aw.phuh_max,
            aw.phuh_avg,
            aw.prouc_min,
            aw.prouc_max,
            aw.prouc_avg,
            aw.prouh_min,
            aw.prouh_max,
            aw.prouh_avg,
            aw.nit_min,
            aw.nit_max,
            aw.nit_avg,
            aw.ket_min,
            aw.ket_max,
            aw.ket_avg,
            aw.leu_min,
            aw.leu_max,
            aw.leu_avg,
            aw.ubg_min,
            aw.ubg_max,
            aw.ubg_avg,
            aw.heartrate_max,
            aw.heartrate_mean,
            aw.heartrate_min,
            aw.sysbp_max,
            aw.sysbp_mean,
            aw.sysbp_min,
            aw.diasbp_max,
            aw.diasbp_mean,
            aw.diasbp_min,
            aw.meanbp_max,
            aw.meanbp_mean,
            aw.meanbp_min,
            aw.resprate_max,
            aw.resprate_mean,
            aw.resprate_min,
            aw.spo2_max,
            aw.spo2_mean,
            aw.spo2_min,
            aw.urineoutput,
            aw.si_max,
            aw.si_mean,
            aw.si_min,
            aw.mingcs,
            aw.weight,
                CASE
                    WHEN (hf.height IS NOT NULL) THEN hf.height
                    WHEN ((hf.height IS NULL) AND (hf.height_chart IS NOT NULL)) THEN hf.height_chart
                    WHEN ((hf.height IS NULL) AND (hf.height_echo IS NOT NULL)) THEN hf.height_echo
                    ELSE NULL::double precision
                END AS height
           FROM (addweight aw
             LEFT JOIN mimiciii.heightfirstday hf ON ((aw.icustay_id = hf.icustay_id)))
        ), addsaps AS (
    --从saps视图中查找患者入ICU后24小时的saps参数
         SELECT ah.subject_id,
            ah.hadm_id,
            ah.icu_length_of_stay,
            ah.icustay_id,
            ah.intime,
            ah.age,
            ah.classlabel,
            ah.po2_min,
            ah.po2_max,
            ah.po2_avg,
            ah.pco2_min,
            ah.pco2_max,
            ah.pco2_avg,
            ah.ph_min,
            ah.ph_max,
            ah.ph_avg,
            ah.potassium_min,
            ah.potassium_max,
            ah.potassium_avg,
            ah.calcium_min,
            ah.calcium_max,
            ah.calcium_avg,
            ah.sodium_min,
            ah.sodium_max,
            ah.sodium_avg,
            ah.chloride_min,
            ah.chloride_max,
            ah.chloride_avg,
            ah.glucose_min,
            ah.glucose_max,
            ah.glucose_avg,
            ah.bicarbonate_min,
            ah.bicarbonate_max,
            ah.bicarbonate_avg,
            ah.be_min,
            ah.be_max,
            ah.be_avg,
            ah.wbc_min,
            ah.wbc_max,
            ah.wbc_avg,
            ah.rbc_min,
            ah.rbc_max,
            ah.rbc_avg,
            ah.platelet_min,
            ah.platelet_max,
            ah.platelet_avg,
            ah.crp_min,
            ah.crp_max,
            ah.crp_avg,
            ah.lactate_min,
            ah.lactate_max,
            ah.lactate_avg,
            ah.alt_min,
            ah.alt_max,
            ah.alt_avg,
            ah.ast_min,
            ah.ast_max,
            ah.ast_avg,
            ah.creatinine_min,
            ah.creatinine_max,
            ah.creatinine_avg,
            ah.bun_min,
            ah.bun_max,
            ah.bun_avg,
            ah.amylase_min,
            ah.amylase_max,
            ah.amylase_avg,
            ah.lipase_min,
            ah.lipase_max,
            ah.lipase_avg,
            ah.pt_min,
            ah.pt_max,
            ah.pt_avg,
            ah.inr_min,
            ah.inr_max,
            ah.inr_avg,
            ah.ddimer_min,
            ah.ddimer_max,
            ah.ddimer_avg,
            ah.fib_min,
            ah.fib_max,
            ah.fib_avg,
            ah.ptt_min,
            ah.ptt_max,
            ah.ptt_avg,
            ah.sg_min,
            ah.sg_max,
            ah.sg_avg,
            ah.gluuc_min,
            ah.gluuc_max,
            ah.gluuc_avg,
            ah.bloodu_min,
            ah.bloodu_max,
            ah.bloodu_avg,
            ah.phuc_min,
            ah.phuc_max,
            ah.phuc_avg,
            ah.phuh_min,
            ah.phuh_max,
            ah.phuh_avg,
            ah.prouc_min,
            ah.prouc_max,
            ah.prouc_avg,
            ah.prouh_min,
            ah.prouh_max,
            ah.prouh_avg,
            ah.nit_min,
            ah.nit_max,
            ah.nit_avg,
            ah.ket_min,
            ah.ket_max,
            ah.ket_avg,
            ah.leu_min,
            ah.leu_max,
            ah.leu_avg,
            ah.ubg_min,
            ah.ubg_max,
            ah.ubg_avg,
            ah.heartrate_max,
            ah.heartrate_mean,
            ah.heartrate_min,
            ah.sysbp_max,
            ah.sysbp_mean,
            ah.sysbp_min,
            ah.diasbp_max,
            ah.diasbp_mean,
            ah.diasbp_min,
            ah.meanbp_max,
            ah.meanbp_mean,
            ah.meanbp_min,
            ah.resprate_max,
            ah.resprate_mean,
            ah.resprate_min,
            ah.spo2_max,
            ah.spo2_mean,
            ah.spo2_min,
            ah.urineoutput,
            ah.si_max,
            ah.si_mean,
            ah.si_min,
            ah.mingcs,
            ah.weight,
            ah.height,
            sa.saps
           FROM (addheight ah
             LEFT JOIN mimiciii.saps sa ON (((ah.subject_id = sa.subject_id) AND (ah.hadm_id = sa.hadm_id) AND (ah.icustay_id = sa.icustay_id))))
        ), addsapsii AS (
    --从sapsii视图中查找患者入ICU后24小时的sapsii评分
         SELECT asa.subject_id,
            asa.hadm_id,
            asa.icu_length_of_stay,
            asa.icustay_id,
            asa.intime,
            asa.age,
            asa.classlabel,
            asa.po2_min,
            asa.po2_max,
            asa.po2_avg,
            asa.pco2_min,
            asa.pco2_max,
            asa.pco2_avg,
            asa.ph_min,
            asa.ph_max,
            asa.ph_avg,
            asa.potassium_min,
            asa.potassium_max,
            asa.potassium_avg,
            asa.calcium_min,
            asa.calcium_max,
            asa.calcium_avg,
            asa.sodium_min,
            asa.sodium_max,
            asa.sodium_avg,
            asa.chloride_min,
            asa.chloride_max,
            asa.chloride_avg,
            asa.glucose_min,
            asa.glucose_max,
            asa.glucose_avg,
            asa.bicarbonate_min,
            asa.bicarbonate_max,
            asa.bicarbonate_avg,
            asa.be_min,
            asa.be_max,
            asa.be_avg,
            asa.wbc_min,
            asa.wbc_max,
            asa.wbc_avg,
            asa.rbc_min,
            asa.rbc_max,
            asa.rbc_avg,
            asa.platelet_min,
            asa.platelet_max,
            asa.platelet_avg,
            asa.crp_min,
            asa.crp_max,
            asa.crp_avg,
            asa.lactate_min,
            asa.lactate_max,
            asa.lactate_avg,
            asa.alt_min,
            asa.alt_max,
            asa.alt_avg,
            asa.ast_min,
            asa.ast_max,
            asa.ast_avg,
            asa.creatinine_min,
            asa.creatinine_max,
            asa.creatinine_avg,
            asa.bun_min,
            asa.bun_max,
            asa.bun_avg,
            asa.amylase_min,
            asa.amylase_max,
            asa.amylase_avg,
            asa.lipase_min,
            asa.lipase_max,
            asa.lipase_avg,
            asa.pt_min,
            asa.pt_max,
            asa.pt_avg,
            asa.inr_min,
            asa.inr_max,
            asa.inr_avg,
            asa.ddimer_min,
            asa.ddimer_max,
            asa.ddimer_avg,
            asa.fib_min,
            asa.fib_max,
            asa.fib_avg,
            asa.ptt_min,
            asa.ptt_max,
            asa.ptt_avg,
            asa.sg_min,
            asa.sg_max,
            asa.sg_avg,
            asa.gluuc_min,
            asa.gluuc_max,
            asa.gluuc_avg,
            asa.bloodu_min,
            asa.bloodu_max,
            asa.bloodu_avg,
            asa.phuc_min,
            asa.phuc_max,
            asa.phuc_avg,
            asa.phuh_min,
            asa.phuh_max,
            asa.phuh_avg,
            asa.prouc_min,
            asa.prouc_max,
            asa.prouc_avg,
            asa.prouh_min,
            asa.prouh_max,
            asa.prouh_avg,
            asa.nit_min,
            asa.nit_max,
            asa.nit_avg,
            asa.ket_min,
            asa.ket_max,
            asa.ket_avg,
            asa.leu_min,
            asa.leu_max,
            asa.leu_avg,
            asa.ubg_min,
            asa.ubg_max,
            asa.ubg_avg,
            asa.heartrate_max,
            asa.heartrate_mean,
            asa.heartrate_min,
            asa.sysbp_max,
            asa.sysbp_mean,
            asa.sysbp_min,
            asa.diasbp_max,
            asa.diasbp_mean,
            asa.diasbp_min,
            asa.meanbp_max,
            asa.meanbp_mean,
            asa.meanbp_min,
            asa.resprate_max,
            asa.resprate_mean,
            asa.resprate_min,
            asa.spo2_max,
            asa.spo2_mean,
            asa.spo2_min,
            asa.urineoutput,
            asa.si_max,
            asa.si_mean,
            asa.si_min,
            asa.mingcs,
            asa.weight,
            asa.height,
            asa.saps,
            saii.sapsii,
            saii.sapsii_prob
           FROM (addsaps asa
             LEFT JOIN mimiciii.sapsii saii ON (((asa.subject_id = saii.subject_id) AND (asa.hadm_id = saii.hadm_id) AND (asa.icustay_id = saii.icustay_id))))
        ), addsofa AS (
    --从sofa视图中查找患者入ICU后24小时的sofa评分
         SELECT as2.subject_id,
            as2.hadm_id,
            as2.icu_length_of_stay,
            as2.icustay_id,
            as2.intime,
            as2.age,
            as2.classlabel,
            as2.po2_min,
            as2.po2_max,
            as2.po2_avg,
            as2.pco2_min,
            as2.pco2_max,
            as2.pco2_avg,
            as2.ph_min,
            as2.ph_max,
            as2.ph_avg,
            as2.potassium_min,
            as2.potassium_max,
            as2.potassium_avg,
            as2.calcium_min,
            as2.calcium_max,
            as2.calcium_avg,
            as2.sodium_min,
            as2.sodium_max,
            as2.sodium_avg,
            as2.chloride_min,
            as2.chloride_max,
            as2.chloride_avg,
            as2.glucose_min,
            as2.glucose_max,
            as2.glucose_avg,
            as2.bicarbonate_min,
            as2.bicarbonate_max,
            as2.bicarbonate_avg,
            as2.be_min,
            as2.be_max,
            as2.be_avg,
            as2.wbc_min,
            as2.wbc_max,
            as2.wbc_avg,
            as2.rbc_min,
            as2.rbc_max,
            as2.rbc_avg,
            as2.platelet_min,
            as2.platelet_max,
            as2.platelet_avg,
            as2.crp_min,
            as2.crp_max,
            as2.crp_avg,
            as2.lactate_min,
            as2.lactate_max,
            as2.lactate_avg,
            as2.alt_min,
            as2.alt_max,
            as2.alt_avg,
            as2.ast_min,
            as2.ast_max,
            as2.ast_avg,
            as2.creatinine_min,
            as2.creatinine_max,
            as2.creatinine_avg,
            as2.bun_min,
            as2.bun_max,
            as2.bun_avg,
            as2.amylase_min,
            as2.amylase_max,
            as2.amylase_avg,
            as2.lipase_min,
            as2.lipase_max,
            as2.lipase_avg,
            as2.pt_min,
            as2.pt_max,
            as2.pt_avg,
            as2.inr_min,
            as2.inr_max,
            as2.inr_avg,
            as2.ddimer_min,
            as2.ddimer_max,
            as2.ddimer_avg,
            as2.fib_min,
            as2.fib_max,
            as2.fib_avg,
            as2.ptt_min,
            as2.ptt_max,
            as2.ptt_avg,
            as2.sg_min,
            as2.sg_max,
            as2.sg_avg,
            as2.gluuc_min,
            as2.gluuc_max,
            as2.gluuc_avg,
            as2.bloodu_min,
            as2.bloodu_max,
            as2.bloodu_avg,
            as2.phuc_min,
            as2.phuc_max,
            as2.phuc_avg,
            as2.phuh_min,
            as2.phuh_max,
            as2.phuh_avg,
            as2.prouc_min,
            as2.prouc_max,
            as2.prouc_avg,
            as2.prouh_min,
            as2.prouh_max,
            as2.prouh_avg,
            as2.nit_min,
            as2.nit_max,
            as2.nit_avg,
            as2.ket_min,
            as2.ket_max,
            as2.ket_avg,
            as2.leu_min,
            as2.leu_max,
            as2.leu_avg,
            as2.ubg_min,
            as2.ubg_max,
            as2.ubg_avg,
            as2.heartrate_max,
            as2.heartrate_mean,
            as2.heartrate_min,
            as2.sysbp_max,
            as2.sysbp_mean,
            as2.sysbp_min,
            as2.diasbp_max,
            as2.diasbp_mean,
            as2.diasbp_min,
            as2.meanbp_max,
            as2.meanbp_mean,
            as2.meanbp_min,
            as2.resprate_max,
            as2.resprate_mean,
            as2.resprate_min,
            as2.spo2_max,
            as2.spo2_mean,
            as2.spo2_min,
            as2.urineoutput,
            as2.si_max,
            as2.si_mean,
            as2.si_min,
            as2.mingcs,
            as2.weight,
            as2.height,
            as2.saps,
            as2.sapsii,
            as2.sapsii_prob,
            sofa.sofa
           FROM (addsapsii as2
             LEFT JOIN mimiciii.sofa ON (((as2.subject_id = sofa.subject_id) AND (as2.hadm_id = sofa.hadm_id) AND (as2.icustay_id = sofa.icustay_id))))
        ), addsirs AS (
    --从sirs视图中查找患者入ICU后24小时的sirs指标
         SELECT addsofa.subject_id,
            addsofa.hadm_id,
            addsofa.icu_length_of_stay,
            addsofa.icustay_id,
            addsofa.intime,
            addsofa.age,
            addsofa.classlabel,
            addsofa.po2_min,
            addsofa.po2_max,
            addsofa.po2_avg,
            addsofa.pco2_min,
            addsofa.pco2_max,
            addsofa.pco2_avg,
            addsofa.ph_min,
            addsofa.ph_max,
            addsofa.ph_avg,
            addsofa.potassium_min,
            addsofa.potassium_max,
            addsofa.potassium_avg,
            addsofa.calcium_min,
            addsofa.calcium_max,
            addsofa.calcium_avg,
            addsofa.sodium_min,
            addsofa.sodium_max,
            addsofa.sodium_avg,
            addsofa.chloride_min,
            addsofa.chloride_max,
            addsofa.chloride_avg,
            addsofa.glucose_min,
            addsofa.glucose_max,
            addsofa.glucose_avg,
            addsofa.bicarbonate_min,
            addsofa.bicarbonate_max,
            addsofa.bicarbonate_avg,
            addsofa.be_min,
            addsofa.be_max,
            addsofa.be_avg,
            addsofa.wbc_min,
            addsofa.wbc_max,
            addsofa.wbc_avg,
            addsofa.rbc_min,
            addsofa.rbc_max,
            addsofa.rbc_avg,
            addsofa.platelet_min,
            addsofa.platelet_max,
            addsofa.platelet_avg,
            addsofa.crp_min,
            addsofa.crp_max,
            addsofa.crp_avg,
            addsofa.lactate_min,
            addsofa.lactate_max,
            addsofa.lactate_avg,
            addsofa.alt_min,
            addsofa.alt_max,
            addsofa.alt_avg,
            addsofa.ast_min,
            addsofa.ast_max,
            addsofa.ast_avg,
            addsofa.creatinine_min,
            addsofa.creatinine_max,
            addsofa.creatinine_avg,
            addsofa.bun_min,
            addsofa.bun_max,
            addsofa.bun_avg,
            addsofa.amylase_min,
            addsofa.amylase_max,
            addsofa.amylase_avg,
            addsofa.lipase_min,
            addsofa.lipase_max,
            addsofa.lipase_avg,
            addsofa.pt_min,
            addsofa.pt_max,
            addsofa.pt_avg,
            addsofa.inr_min,
            addsofa.inr_max,
            addsofa.inr_avg,
            addsofa.ddimer_min,
            addsofa.ddimer_max,
            addsofa.ddimer_avg,
            addsofa.fib_min,
            addsofa.fib_max,
            addsofa.fib_avg,
            addsofa.ptt_min,
            addsofa.ptt_max,
            addsofa.ptt_avg,
            addsofa.sg_min,
            addsofa.sg_max,
            addsofa.sg_avg,
            addsofa.gluuc_min,
            addsofa.gluuc_max,
            addsofa.gluuc_avg,
            addsofa.bloodu_min,
            addsofa.bloodu_max,
            addsofa.bloodu_avg,
            addsofa.phuc_min,
            addsofa.phuc_max,
            addsofa.phuc_avg,
            addsofa.phuh_min,
            addsofa.phuh_max,
            addsofa.phuh_avg,
            addsofa.prouc_min,
            addsofa.prouc_max,
            addsofa.prouc_avg,
            addsofa.prouh_min,
            addsofa.prouh_max,
            addsofa.prouh_avg,
            addsofa.nit_min,
            addsofa.nit_max,
            addsofa.nit_avg,
            addsofa.ket_min,
            addsofa.ket_max,
            addsofa.ket_avg,
            addsofa.leu_min,
            addsofa.leu_max,
            addsofa.leu_avg,
            addsofa.ubg_min,
            addsofa.ubg_max,
            addsofa.ubg_avg,
            addsofa.heartrate_max,
            addsofa.heartrate_mean,
            addsofa.heartrate_min,
            addsofa.sysbp_max,
            addsofa.sysbp_mean,
            addsofa.sysbp_min,
            addsofa.diasbp_max,
            addsofa.diasbp_mean,
            addsofa.diasbp_min,
            addsofa.meanbp_max,
            addsofa.meanbp_mean,
            addsofa.meanbp_min,
            addsofa.resprate_max,
            addsofa.resprate_mean,
            addsofa.resprate_min,
            addsofa.spo2_max,
            addsofa.spo2_mean,
            addsofa.spo2_min,
            addsofa.urineoutput,
            addsofa.si_max,
            addsofa.si_mean,
            addsofa.si_min,
            addsofa.mingcs,
            addsofa.weight,
            addsofa.height,
            addsofa.saps,
            addsofa.sapsii,
            addsofa.sapsii_prob,
            addsofa.sofa,
            sirs.sirs
           FROM (addsofa
             LEFT JOIN mimiciii.sirs ON (((addsofa.subject_id = sirs.subject_id) AND (addsofa.hadm_id = sirs.hadm_id) AND (addsofa.icustay_id = sirs.icustay_id))))
        ), addaps3 AS (
    --从apsiii视图中查找患者入ICU后24小时的apsiii评分
         SELECT addsirs.subject_id,
            addsirs.hadm_id,
            addsirs.icu_length_of_stay,
            addsirs.icustay_id,
            addsirs.intime,
            addsirs.age,
            addsirs.classlabel,
            addsirs.po2_min,
            addsirs.po2_max,
            addsirs.po2_avg,
            addsirs.pco2_min,
            addsirs.pco2_max,
            addsirs.pco2_avg,
            addsirs.ph_min,
            addsirs.ph_max,
            addsirs.ph_avg,
            addsirs.potassium_min,
            addsirs.potassium_max,
            addsirs.potassium_avg,
            addsirs.calcium_min,
            addsirs.calcium_max,
            addsirs.calcium_avg,
            addsirs.sodium_min,
            addsirs.sodium_max,
            addsirs.sodium_avg,
            addsirs.chloride_min,
            addsirs.chloride_max,
            addsirs.chloride_avg,
            addsirs.glucose_min,
            addsirs.glucose_max,
            addsirs.glucose_avg,
            addsirs.bicarbonate_min,
            addsirs.bicarbonate_max,
            addsirs.bicarbonate_avg,
            addsirs.be_min,
            addsirs.be_max,
            addsirs.be_avg,
            addsirs.wbc_min,
            addsirs.wbc_max,
            addsirs.wbc_avg,
            addsirs.rbc_min,
            addsirs.rbc_max,
            addsirs.rbc_avg,
            addsirs.platelet_min,
            addsirs.platelet_max,
            addsirs.platelet_avg,
            addsirs.crp_min,
            addsirs.crp_max,
            addsirs.crp_avg,
            addsirs.lactate_min,
            addsirs.lactate_max,
            addsirs.lactate_avg,
            addsirs.alt_min,
            addsirs.alt_max,
            addsirs.alt_avg,
            addsirs.ast_min,
            addsirs.ast_max,
            addsirs.ast_avg,
            addsirs.creatinine_min,
            addsirs.creatinine_max,
            addsirs.creatinine_avg,
            addsirs.bun_min,
            addsirs.bun_max,
            addsirs.bun_avg,
            addsirs.amylase_min,
            addsirs.amylase_max,
            addsirs.amylase_avg,
            addsirs.lipase_min,
            addsirs.lipase_max,
            addsirs.lipase_avg,
            addsirs.pt_min,
            addsirs.pt_max,
            addsirs.pt_avg,
            addsirs.inr_min,
            addsirs.inr_max,
            addsirs.inr_avg,
            addsirs.ddimer_min,
            addsirs.ddimer_max,
            addsirs.ddimer_avg,
            addsirs.fib_min,
            addsirs.fib_max,
            addsirs.fib_avg,
            addsirs.ptt_min,
            addsirs.ptt_max,
            addsirs.ptt_avg,
            addsirs.sg_min,
            addsirs.sg_max,
            addsirs.sg_avg,
            addsirs.gluuc_min,
            addsirs.gluuc_max,
            addsirs.gluuc_avg,
            addsirs.bloodu_min,
            addsirs.bloodu_max,
            addsirs.bloodu_avg,
            addsirs.phuc_min,
            addsirs.phuc_max,
            addsirs.phuc_avg,
            addsirs.phuh_min,
            addsirs.phuh_max,
            addsirs.phuh_avg,
            addsirs.prouc_min,
            addsirs.prouc_max,
            addsirs.prouc_avg,
            addsirs.prouh_min,
            addsirs.prouh_max,
            addsirs.prouh_avg,
            addsirs.nit_min,
            addsirs.nit_max,
            addsirs.nit_avg,
            addsirs.ket_min,
            addsirs.ket_max,
            addsirs.ket_avg,
            addsirs.leu_min,
            addsirs.leu_max,
            addsirs.leu_avg,
            addsirs.ubg_min,
            addsirs.ubg_max,
            addsirs.ubg_avg,
            addsirs.heartrate_max,
            addsirs.heartrate_mean,
            addsirs.heartrate_min,
            addsirs.sysbp_max,
            addsirs.sysbp_mean,
            addsirs.sysbp_min,
            addsirs.diasbp_max,
            addsirs.diasbp_mean,
            addsirs.diasbp_min,
            addsirs.meanbp_max,
            addsirs.meanbp_mean,
            addsirs.meanbp_min,
            addsirs.resprate_max,
            addsirs.resprate_mean,
            addsirs.resprate_min,
            addsirs.spo2_max,
            addsirs.spo2_mean,
            addsirs.spo2_min,
            addsirs.urineoutput,
            addsirs.si_max,
            addsirs.si_mean,
            addsirs.si_min,
            addsirs.mingcs,
            addsirs.weight,
            addsirs.height,
            addsirs.saps,
            addsirs.sapsii,
            addsirs.sapsii_prob,
            addsirs.sofa,
            addsirs.sirs,
            apsiii.apsiii,
            apsiii.apsiii_prob
           FROM (addsirs
             LEFT JOIN mimiciii.apsiii ON (((addsirs.subject_id = apsiii.subject_id) AND (addsirs.hadm_id = apsiii.hadm_id) AND (addsirs.icustay_id = apsiii.icustay_id))))
        ), addoasis AS (
    --从oasis视图中提取患者入ICU后24小时的oasis评分
         SELECT addaps3.subject_id,
            addaps3.hadm_id,
            addaps3.icu_length_of_stay,
            addaps3.icustay_id,
            addaps3.intime,
            addaps3.age,
            addaps3.classlabel,
            addaps3.po2_min,
            addaps3.po2_max,
            addaps3.po2_avg,
            addaps3.pco2_min,
            addaps3.pco2_max,
            addaps3.pco2_avg,
            addaps3.ph_min,
            addaps3.ph_max,
            addaps3.ph_avg,
            addaps3.potassium_min,
            addaps3.potassium_max,
            addaps3.potassium_avg,
            addaps3.calcium_min,
            addaps3.calcium_max,
            addaps3.calcium_avg,
            addaps3.sodium_min,
            addaps3.sodium_max,
            addaps3.sodium_avg,
            addaps3.chloride_min,
            addaps3.chloride_max,
            addaps3.chloride_avg,
            addaps3.glucose_min,
            addaps3.glucose_max,
            addaps3.glucose_avg,
            addaps3.bicarbonate_min,
            addaps3.bicarbonate_max,
            addaps3.bicarbonate_avg,
            addaps3.be_min,
            addaps3.be_max,
            addaps3.be_avg,
            addaps3.wbc_min,
            addaps3.wbc_max,
            addaps3.wbc_avg,
            addaps3.rbc_min,
            addaps3.rbc_max,
            addaps3.rbc_avg,
            addaps3.platelet_min,
            addaps3.platelet_max,
            addaps3.platelet_avg,
            addaps3.crp_min,
            addaps3.crp_max,
            addaps3.crp_avg,
            addaps3.lactate_min,
            addaps3.lactate_max,
            addaps3.lactate_avg,
            addaps3.alt_min,
            addaps3.alt_max,
            addaps3.alt_avg,
            addaps3.ast_min,
            addaps3.ast_max,
            addaps3.ast_avg,
            addaps3.creatinine_min,
            addaps3.creatinine_max,
            addaps3.creatinine_avg,
            addaps3.bun_min,
            addaps3.bun_max,
            addaps3.bun_avg,
            addaps3.amylase_min,
            addaps3.amylase_max,
            addaps3.amylase_avg,
            addaps3.lipase_min,
            addaps3.lipase_max,
            addaps3.lipase_avg,
            addaps3.pt_min,
            addaps3.pt_max,
            addaps3.pt_avg,
            addaps3.inr_min,
            addaps3.inr_max,
            addaps3.inr_avg,
            addaps3.ddimer_min,
            addaps3.ddimer_max,
            addaps3.ddimer_avg,
            addaps3.fib_min,
            addaps3.fib_max,
            addaps3.fib_avg,
            addaps3.ptt_min,
            addaps3.ptt_max,
            addaps3.ptt_avg,
            addaps3.sg_min,
            addaps3.sg_max,
            addaps3.sg_avg,
            addaps3.gluuc_min,
            addaps3.gluuc_max,
            addaps3.gluuc_avg,
            addaps3.bloodu_min,
            addaps3.bloodu_max,
            addaps3.bloodu_avg,
            addaps3.phuc_min,
            addaps3.phuc_max,
            addaps3.phuc_avg,
            addaps3.phuh_min,
            addaps3.phuh_max,
            addaps3.phuh_avg,
            addaps3.prouc_min,
            addaps3.prouc_max,
            addaps3.prouc_avg,
            addaps3.prouh_min,
            addaps3.prouh_max,
            addaps3.prouh_avg,
            addaps3.nit_min,
            addaps3.nit_max,
            addaps3.nit_avg,
            addaps3.ket_min,
            addaps3.ket_max,
            addaps3.ket_avg,
            addaps3.leu_min,
            addaps3.leu_max,
            addaps3.leu_avg,
            addaps3.ubg_min,
            addaps3.ubg_max,
            addaps3.ubg_avg,
            addaps3.heartrate_max,
            addaps3.heartrate_mean,
            addaps3.heartrate_min,
            addaps3.sysbp_max,
            addaps3.sysbp_mean,
            addaps3.sysbp_min,
            addaps3.diasbp_max,
            addaps3.diasbp_mean,
            addaps3.diasbp_min,
            addaps3.meanbp_max,
            addaps3.meanbp_mean,
            addaps3.meanbp_min,
            addaps3.resprate_max,
            addaps3.resprate_mean,
            addaps3.resprate_min,
            addaps3.spo2_max,
            addaps3.spo2_mean,
            addaps3.spo2_min,
            addaps3.urineoutput,
            addaps3.si_max,
            addaps3.si_mean,
            addaps3.si_min,
            addaps3.mingcs,
            addaps3.weight,
            addaps3.height,
            addaps3.saps,
            addaps3.sapsii,
            addaps3.sapsii_prob,
            addaps3.sofa,
            addaps3.sirs,
            addaps3.apsiii,
            addaps3.apsiii_prob,
            oasis.oasis,
            oasis.oasis_prob
           FROM (addaps3
             LEFT JOIN mimiciii.oasis ON (((addaps3.subject_id = oasis.subject_id) AND (addaps3.hadm_id = oasis.hadm_id) AND (addaps3.icustay_id = oasis.icustay_id))))
        ), addlods AS (
    --从lods视图中提取患者入ICU后24小时的lods评分
         SELECT addoasis.subject_id,
            addoasis.hadm_id,
            addoasis.icu_length_of_stay,
            addoasis.icustay_id,
            addoasis.intime,
            addoasis.age,
            addoasis.classlabel,
            addoasis.po2_min,
            addoasis.po2_max,
            addoasis.po2_avg,
            addoasis.pco2_min,
            addoasis.pco2_max,
            addoasis.pco2_avg,
            addoasis.ph_min,
            addoasis.ph_max,
            addoasis.ph_avg,
            addoasis.potassium_min,
            addoasis.potassium_max,
            addoasis.potassium_avg,
            addoasis.calcium_min,
            addoasis.calcium_max,
            addoasis.calcium_avg,
            addoasis.sodium_min,
            addoasis.sodium_max,
            addoasis.sodium_avg,
            addoasis.chloride_min,
            addoasis.chloride_max,
            addoasis.chloride_avg,
            addoasis.glucose_min,
            addoasis.glucose_max,
            addoasis.glucose_avg,
            addoasis.bicarbonate_min,
            addoasis.bicarbonate_max,
            addoasis.bicarbonate_avg,
            addoasis.be_min,
            addoasis.be_max,
            addoasis.be_avg,
            addoasis.wbc_min,
            addoasis.wbc_max,
            addoasis.wbc_avg,
            addoasis.rbc_min,
            addoasis.rbc_max,
            addoasis.rbc_avg,
            addoasis.platelet_min,
            addoasis.platelet_max,
            addoasis.platelet_avg,
            addoasis.crp_min,
            addoasis.crp_max,
            addoasis.crp_avg,
            addoasis.lactate_min,
            addoasis.lactate_max,
            addoasis.lactate_avg,
            addoasis.alt_min,
            addoasis.alt_max,
            addoasis.alt_avg,
            addoasis.ast_min,
            addoasis.ast_max,
            addoasis.ast_avg,
            addoasis.creatinine_min,
            addoasis.creatinine_max,
            addoasis.creatinine_avg,
            addoasis.bun_min,
            addoasis.bun_max,
            addoasis.bun_avg,
            addoasis.amylase_min,
            addoasis.amylase_max,
            addoasis.amylase_avg,
            addoasis.lipase_min,
            addoasis.lipase_max,
            addoasis.lipase_avg,
            addoasis.pt_min,
            addoasis.pt_max,
            addoasis.pt_avg,
            addoasis.inr_min,
            addoasis.inr_max,
            addoasis.inr_avg,
            addoasis.ddimer_min,
            addoasis.ddimer_max,
            addoasis.ddimer_avg,
            addoasis.fib_min,
            addoasis.fib_max,
            addoasis.fib_avg,
            addoasis.ptt_min,
            addoasis.ptt_max,
            addoasis.ptt_avg,
            addoasis.sg_min,
            addoasis.sg_max,
            addoasis.sg_avg,
            addoasis.gluuc_min,
            addoasis.gluuc_max,
            addoasis.gluuc_avg,
            addoasis.bloodu_min,
            addoasis.bloodu_max,
            addoasis.bloodu_avg,
            addoasis.phuc_min,
            addoasis.phuc_max,
            addoasis.phuc_avg,
            addoasis.phuh_min,
            addoasis.phuh_max,
            addoasis.phuh_avg,
            addoasis.prouc_min,
            addoasis.prouc_max,
            addoasis.prouc_avg,
            addoasis.prouh_min,
            addoasis.prouh_max,
            addoasis.prouh_avg,
            addoasis.nit_min,
            addoasis.nit_max,
            addoasis.nit_avg,
            addoasis.ket_min,
            addoasis.ket_max,
            addoasis.ket_avg,
            addoasis.leu_min,
            addoasis.leu_max,
            addoasis.leu_avg,
            addoasis.ubg_min,
            addoasis.ubg_max,
            addoasis.ubg_avg,
            addoasis.heartrate_max,
            addoasis.heartrate_mean,
            addoasis.heartrate_min,
            addoasis.sysbp_max,
            addoasis.sysbp_mean,
            addoasis.sysbp_min,
            addoasis.diasbp_max,
            addoasis.diasbp_mean,
            addoasis.diasbp_min,
            addoasis.meanbp_max,
            addoasis.meanbp_mean,
            addoasis.meanbp_min,
            addoasis.resprate_max,
            addoasis.resprate_mean,
            addoasis.resprate_min,
            addoasis.spo2_max,
            addoasis.spo2_mean,
            addoasis.spo2_min,
            addoasis.urineoutput,
            addoasis.si_max,
            addoasis.si_mean,
            addoasis.si_min,
            addoasis.mingcs,
            addoasis.weight,
            addoasis.height,
            addoasis.saps,
            addoasis.sapsii,
            addoasis.sapsii_prob,
            addoasis.sofa,
            addoasis.sirs,
            addoasis.apsiii,
            addoasis.apsiii_prob,
            addoasis.oasis,
            addoasis.oasis_prob,
            lods.lods
           FROM (addoasis
             LEFT JOIN mimiciii.lods ON (((addoasis.icustay_id = lods.icustay_id) AND (addoasis.subject_id = lods.subject_id) AND (addoasis.hadm_id = lods.hadm_id))))
        ), addvent AS (
    --从ventdurations视图中通过机械通气开始时间判断患者入ICU后第一天是否进行机械通气
    --也可以通过ventfirst视图直接进行查找
         SELECT ao.subject_id,
            ao.hadm_id,
            ao.icu_length_of_stay,
            ao.icustay_id,
            ao.intime,
            ao.age,
            ao.classlabel,
            ao.po2_min,
            ao.po2_max,
            ao.po2_avg,
            ao.pco2_min,
            ao.pco2_max,
            ao.pco2_avg,
            ao.ph_min,
            ao.ph_max,
            ao.ph_avg,
            ao.potassium_min,
            ao.potassium_max,
            ao.potassium_avg,
            ao.calcium_min,
            ao.calcium_max,
            ao.calcium_avg,
            ao.sodium_min,
            ao.sodium_max,
            ao.sodium_avg,
            ao.chloride_min,
            ao.chloride_max,
            ao.chloride_avg,
            ao.glucose_min,
            ao.glucose_max,
            ao.glucose_avg,
            ao.bicarbonate_min,
            ao.bicarbonate_max,
            ao.bicarbonate_avg,
            ao.be_min,
            ao.be_max,
            ao.be_avg,
            ao.wbc_min,
            ao.wbc_max,
            ao.wbc_avg,
            ao.rbc_min,
            ao.rbc_max,
            ao.rbc_avg,
            ao.platelet_min,
            ao.platelet_max,
            ao.platelet_avg,
            ao.crp_min,
            ao.crp_max,
            ao.crp_avg,
            ao.lactate_min,
            ao.lactate_max,
            ao.lactate_avg,
            ao.alt_min,
            ao.alt_max,
            ao.alt_avg,
            ao.ast_min,
            ao.ast_max,
            ao.ast_avg,
            ao.creatinine_min,
            ao.creatinine_max,
            ao.creatinine_avg,
            ao.bun_min,
            ao.bun_max,
            ao.bun_avg,
            ao.amylase_min,
            ao.amylase_max,
            ao.amylase_avg,
            ao.lipase_min,
            ao.lipase_max,
            ao.lipase_avg,
            ao.pt_min,
            ao.pt_max,
            ao.pt_avg,
            ao.inr_min,
            ao.inr_max,
            ao.inr_avg,
            ao.ddimer_min,
            ao.ddimer_max,
            ao.ddimer_avg,
            ao.fib_min,
            ao.fib_max,
            ao.fib_avg,
            ao.ptt_min,
            ao.ptt_max,
            ao.ptt_avg,
            ao.sg_min,
            ao.sg_max,
            ao.sg_avg,
            ao.gluuc_min,
            ao.gluuc_max,
            ao.gluuc_avg,
            ao.bloodu_min,
            ao.bloodu_max,
            ao.bloodu_avg,
            ao.phuc_min,
            ao.phuc_max,
            ao.phuc_avg,
            ao.phuh_min,
            ao.phuh_max,
            ao.phuh_avg,
            ao.prouc_min,
            ao.prouc_max,
            ao.prouc_avg,
            ao.prouh_min,
            ao.prouh_max,
            ao.prouh_avg,
            ao.nit_min,
            ao.nit_max,
            ao.nit_avg,
            ao.ket_min,
            ao.ket_max,
            ao.ket_avg,
            ao.leu_min,
            ao.leu_max,
            ao.leu_avg,
            ao.ubg_min,
            ao.ubg_max,
            ao.ubg_avg,
            ao.heartrate_max,
            ao.heartrate_mean,
            ao.heartrate_min,
            ao.sysbp_max,
            ao.sysbp_mean,
            ao.sysbp_min,
            ao.diasbp_max,
            ao.diasbp_mean,
            ao.diasbp_min,
            ao.meanbp_max,
            ao.meanbp_mean,
            ao.meanbp_min,
            ao.resprate_max,
            ao.resprate_mean,
            ao.resprate_min,
            ao.spo2_max,
            ao.spo2_mean,
            ao.spo2_min,
            ao.urineoutput,
            ao.si_max,
            ao.si_mean,
            ao.si_min,
            ao.mingcs,
            ao.weight,
            ao.height,
            ao.saps,
            ao.sapsii,
            ao.sapsii_prob,
            ao.sofa,
            ao.sirs,
            ao.apsiii,
            ao.apsiii_prob,
            ao.oasis,
            ao.oasis_prob,
            ao.lods,
                CASE
                    WHEN ((vd.starttime >= ao.intime) AND (vd.starttime <= (ao.intime + '1 day'::interval day))) THEN 1
                    ELSE 0
                END AS vent
           FROM (addlods ao
             LEFT JOIN mimiciii.ventdurations vd ON (((vd.icustay_id = ao.icustay_id) AND ((vd.starttime >= ao.intime) AND (vd.starttime <= (ao.intime + '1 day'::interval day))) AND (vd.ventnum = 1))))
        ), addvaso AS (
    --通过vasopressordurations视图判断患者入ICU后24小时是否使用了血管活性药物
         SELECT av.subject_id,
            av.hadm_id,
            av.icu_length_of_stay,
            av.icustay_id,
            av.intime,
            av.age,
            av.classlabel,
            av.po2_min,
            av.po2_max,
            av.po2_avg,
            av.pco2_min,
            av.pco2_max,
            av.pco2_avg,
            av.ph_min,
            av.ph_max,
            av.ph_avg,
            av.potassium_min,
            av.potassium_max,
            av.potassium_avg,
            av.calcium_min,
            av.calcium_max,
            av.calcium_avg,
            av.sodium_min,
            av.sodium_max,
            av.sodium_avg,
            av.chloride_min,
            av.chloride_max,
            av.chloride_avg,
            av.glucose_min,
            av.glucose_max,
            av.glucose_avg,
            av.bicarbonate_min,
            av.bicarbonate_max,
            av.bicarbonate_avg,
            av.be_min,
            av.be_max,
            av.be_avg,
            av.wbc_min,
            av.wbc_max,
            av.wbc_avg,
            av.rbc_min,
            av.rbc_max,
            av.rbc_avg,
            av.platelet_min,
            av.platelet_max,
            av.platelet_avg,
            av.crp_min,
            av.crp_max,
            av.crp_avg,
            av.lactate_min,
            av.lactate_max,
            av.lactate_avg,
            av.alt_min,
            av.alt_max,
            av.alt_avg,
            av.ast_min,
            av.ast_max,
            av.ast_avg,
            av.creatinine_min,
            av.creatinine_max,
            av.creatinine_avg,
            av.bun_min,
            av.bun_max,
            av.bun_avg,
            av.amylase_min,
            av.amylase_max,
            av.amylase_avg,
            av.lipase_min,
            av.lipase_max,
            av.lipase_avg,
            av.pt_min,
            av.pt_max,
            av.pt_avg,
            av.inr_min,
            av.inr_max,
            av.inr_avg,
            av.ddimer_min,
            av.ddimer_max,
            av.ddimer_avg,
            av.fib_min,
            av.fib_max,
            av.fib_avg,
            av.ptt_min,
            av.ptt_max,
            av.ptt_avg,
            av.sg_min,
            av.sg_max,
            av.sg_avg,
            av.gluuc_min,
            av.gluuc_max,
            av.gluuc_avg,
            av.bloodu_min,
            av.bloodu_max,
            av.bloodu_avg,
            av.phuc_min,
            av.phuc_max,
            av.phuc_avg,
            av.phuh_min,
            av.phuh_max,
            av.phuh_avg,
            av.prouc_min,
            av.prouc_max,
            av.prouc_avg,
            av.prouh_min,
            av.prouh_max,
            av.prouh_avg,
            av.nit_min,
            av.nit_max,
            av.nit_avg,
            av.ket_min,
            av.ket_max,
            av.ket_avg,
            av.leu_min,
            av.leu_max,
            av.leu_avg,
            av.ubg_min,
            av.ubg_max,
            av.ubg_avg,
            av.heartrate_max,
            av.heartrate_mean,
            av.heartrate_min,
            av.sysbp_max,
            av.sysbp_mean,
            av.sysbp_min,
            av.diasbp_max,
            av.diasbp_mean,
            av.diasbp_min,
            av.meanbp_max,
            av.meanbp_mean,
            av.meanbp_min,
            av.resprate_max,
            av.resprate_mean,
            av.resprate_min,
            av.spo2_max,
            av.spo2_mean,
            av.spo2_min,
            av.urineoutput,
            av.si_max,
            av.si_mean,
            av.si_min,
            av.mingcs,
            av.weight,
            av.height,
            av.saps,
            av.sapsii,
            av.sapsii_prob,
            av.sofa,
            av.sirs,
            av.apsiii,
            av.apsiii_prob,
            av.oasis,
            av.oasis_prob,
            av.lods,
            av.vent,
                CASE
                    WHEN ((va.starttime >= av.intime) AND (va.starttime <= (av.intime + '1 day'::interval day))) THEN 1
                    ELSE 0
                END AS vaso
           FROM (addvent av
             LEFT JOIN mimiciii.vasopressordurations va ON (((av.icustay_id = va.icustay_id) AND ((va.starttime >= av.intime) AND (va.starttime <= (av.intime + '1 day'::interval day))) AND (va.vasonum = 1))))
        ), adddiuretic AS (
    --从yj_diureticdurations视图中提取患者在入ICU后24小时内是否使用了利尿剂
         SELECT avaso.subject_id,
            avaso.hadm_id,
            avaso.icu_length_of_stay,
            avaso.icustay_id,
            avaso.intime,
            avaso.age,
            avaso.classlabel,
            avaso.po2_min,
            avaso.po2_max,
            avaso.po2_avg,
            avaso.pco2_min,
            avaso.pco2_max,
            avaso.pco2_avg,
            avaso.ph_min,
            avaso.ph_max,
            avaso.ph_avg,
            avaso.potassium_min,
            avaso.potassium_max,
            avaso.potassium_avg,
            avaso.calcium_min,
            avaso.calcium_max,
            avaso.calcium_avg,
            avaso.sodium_min,
            avaso.sodium_max,
            avaso.sodium_avg,
            avaso.chloride_min,
            avaso.chloride_max,
            avaso.chloride_avg,
            avaso.glucose_min,
            avaso.glucose_max,
            avaso.glucose_avg,
            avaso.bicarbonate_min,
            avaso.bicarbonate_max,
            avaso.bicarbonate_avg,
            avaso.be_min,
            avaso.be_max,
            avaso.be_avg,
            avaso.wbc_min,
            avaso.wbc_max,
            avaso.wbc_avg,
            avaso.rbc_min,
            avaso.rbc_max,
            avaso.rbc_avg,
            avaso.platelet_min,
            avaso.platelet_max,
            avaso.platelet_avg,
            avaso.crp_min,
            avaso.crp_max,
            avaso.crp_avg,
            avaso.lactate_min,
            avaso.lactate_max,
            avaso.lactate_avg,
            avaso.alt_min,
            avaso.alt_max,
            avaso.alt_avg,
            avaso.ast_min,
            avaso.ast_max,
            avaso.ast_avg,
            avaso.creatinine_min,
            avaso.creatinine_max,
            avaso.creatinine_avg,
            avaso.bun_min,
            avaso.bun_max,
            avaso.bun_avg,
            avaso.amylase_min,
            avaso.amylase_max,
            avaso.amylase_avg,
            avaso.lipase_min,
            avaso.lipase_max,
            avaso.lipase_avg,
            avaso.pt_min,
            avaso.pt_max,
            avaso.pt_avg,
            avaso.inr_min,
            avaso.inr_max,
            avaso.inr_avg,
            avaso.ddimer_min,
            avaso.ddimer_max,
            avaso.ddimer_avg,
            avaso.fib_min,
            avaso.fib_max,
            avaso.fib_avg,
            avaso.ptt_min,
            avaso.ptt_max,
            avaso.ptt_avg,
            avaso.sg_min,
            avaso.sg_max,
            avaso.sg_avg,
            avaso.gluuc_min,
            avaso.gluuc_max,
            avaso.gluuc_avg,
            avaso.bloodu_min,
            avaso.bloodu_max,
            avaso.bloodu_avg,
            avaso.phuc_min,
            avaso.phuc_max,
            avaso.phuc_avg,
            avaso.phuh_min,
            avaso.phuh_max,
            avaso.phuh_avg,
            avaso.prouc_min,
            avaso.prouc_max,
            avaso.prouc_avg,
            avaso.prouh_min,
            avaso.prouh_max,
            avaso.prouh_avg,
            avaso.nit_min,
            avaso.nit_max,
            avaso.nit_avg,
            avaso.ket_min,
            avaso.ket_max,
            avaso.ket_avg,
            avaso.leu_min,
            avaso.leu_max,
            avaso.leu_avg,
            avaso.ubg_min,
            avaso.ubg_max,
            avaso.ubg_avg,
            avaso.heartrate_max,
            avaso.heartrate_mean,
            avaso.heartrate_min,
            avaso.sysbp_max,
            avaso.sysbp_mean,
            avaso.sysbp_min,
            avaso.diasbp_max,
            avaso.diasbp_mean,
            avaso.diasbp_min,
            avaso.meanbp_max,
            avaso.meanbp_mean,
            avaso.meanbp_min,
            avaso.resprate_max,
            avaso.resprate_mean,
            avaso.resprate_min,
            avaso.spo2_max,
            avaso.spo2_mean,
            avaso.spo2_min,
            avaso.urineoutput,
            avaso.si_max,
            avaso.si_mean,
            avaso.si_min,
            avaso.mingcs,
            avaso.weight,
            avaso.height,
            avaso.saps,
            avaso.sapsii,
            avaso.sapsii_prob,
            avaso.sofa,
            avaso.sirs,
            avaso.apsiii,
            avaso.apsiii_prob,
            avaso.oasis,
            avaso.oasis_prob,
            avaso.lods,
            avaso.vent,
            avaso.vaso,
                CASE
                    WHEN ((yd.starttime >= avaso.intime) AND (yd.starttime <= (avaso.intime + '1 day'::interval day))) THEN 1
                    ELSE 0
                END AS diuretic
           FROM (addvaso avaso
             LEFT JOIN mimiciii.yj_diureticdurations yd ON (((avaso.icustay_id = yd.icustay_id) AND ((yd.starttime >= avaso.intime) AND (yd.starttime <= (avaso.intime + '1 day'::interval day))) AND (yd.vasonum = 1))))
        )
    --汇总上述所有参数，并添加患者出院是否死亡信息
 SELECT DISTINCT adddiuretic.subject_id,
    adddiuretic.hadm_id,
    adddiuretic.icu_length_of_stay,
    adddiuretic.icustay_id,
    adddiuretic.intime,
    adddiuretic.age,
    adddiuretic.classlabel,
    adddiuretic.po2_min,
    adddiuretic.po2_max,
    adddiuretic.po2_avg,
    adddiuretic.pco2_min,
    adddiuretic.pco2_max,
    adddiuretic.pco2_avg,
    adddiuretic.ph_min,
    adddiuretic.ph_max,
    adddiuretic.ph_avg,
    adddiuretic.potassium_min,
    adddiuretic.potassium_max,
    adddiuretic.potassium_avg,
    adddiuretic.calcium_min,
    adddiuretic.calcium_max,
    adddiuretic.calcium_avg,
    adddiuretic.sodium_min,
    adddiuretic.sodium_max,
    adddiuretic.sodium_avg,
    adddiuretic.chloride_min,
    adddiuretic.chloride_max,
    adddiuretic.chloride_avg,
    adddiuretic.glucose_min,
    adddiuretic.glucose_max,
    adddiuretic.glucose_avg,
    adddiuretic.bicarbonate_min,
    adddiuretic.bicarbonate_max,
    adddiuretic.bicarbonate_avg,
    adddiuretic.be_min,
    adddiuretic.be_max,
    adddiuretic.be_avg,
    adddiuretic.wbc_min,
    adddiuretic.wbc_max,
    adddiuretic.wbc_avg,
    adddiuretic.rbc_min,
    adddiuretic.rbc_max,
    adddiuretic.rbc_avg,
    adddiuretic.platelet_min,
    adddiuretic.platelet_max,
    adddiuretic.platelet_avg,
    adddiuretic.crp_min,
    adddiuretic.crp_max,
    adddiuretic.crp_avg,
    adddiuretic.lactate_min,
    adddiuretic.lactate_max,
    adddiuretic.lactate_avg,
    adddiuretic.alt_min,
    adddiuretic.alt_max,
    adddiuretic.alt_avg,
    adddiuretic.ast_min,
    adddiuretic.ast_max,
    adddiuretic.ast_avg,
    adddiuretic.creatinine_min,
    adddiuretic.creatinine_max,
    adddiuretic.creatinine_avg,
    adddiuretic.bun_min,
    adddiuretic.bun_max,
    adddiuretic.bun_avg,
    adddiuretic.amylase_min,
    adddiuretic.amylase_max,
    adddiuretic.amylase_avg,
    adddiuretic.lipase_min,
    adddiuretic.lipase_max,
    adddiuretic.lipase_avg,
    adddiuretic.pt_min,
    adddiuretic.pt_max,
    adddiuretic.pt_avg,
    adddiuretic.inr_min,
    adddiuretic.inr_max,
    adddiuretic.inr_avg,
    adddiuretic.ddimer_min,
    adddiuretic.ddimer_max,
    adddiuretic.ddimer_avg,
    adddiuretic.fib_min,
    adddiuretic.fib_max,
    adddiuretic.fib_avg,
    adddiuretic.ptt_min,
    adddiuretic.ptt_max,
    adddiuretic.ptt_avg,
    adddiuretic.sg_min,
    adddiuretic.sg_max,
    adddiuretic.sg_avg,
    adddiuretic.gluuc_min,
    adddiuretic.gluuc_max,
    adddiuretic.gluuc_avg,
    adddiuretic.bloodu_min,
    adddiuretic.bloodu_max,
    adddiuretic.bloodu_avg,
    adddiuretic.phuc_min,
    adddiuretic.phuc_max,
    adddiuretic.phuc_avg,
    adddiuretic.phuh_min,
    adddiuretic.phuh_max,
    adddiuretic.phuh_avg,
    adddiuretic.prouc_min,
    adddiuretic.prouc_max,
    adddiuretic.prouc_avg,
    adddiuretic.prouh_min,
    adddiuretic.prouh_max,
    adddiuretic.prouh_avg,
    adddiuretic.nit_min,
    adddiuretic.nit_max,
    adddiuretic.nit_avg,
    adddiuretic.ket_min,
    adddiuretic.ket_max,
    adddiuretic.ket_avg,
    adddiuretic.leu_min,
    adddiuretic.leu_max,
    adddiuretic.leu_avg,
    adddiuretic.ubg_min,
    adddiuretic.ubg_max,
    adddiuretic.ubg_avg,
    adddiuretic.heartrate_max,
    adddiuretic.heartrate_mean,
    adddiuretic.heartrate_min,
    adddiuretic.sysbp_max,
    adddiuretic.sysbp_mean,
    adddiuretic.sysbp_min,
    adddiuretic.diasbp_max,
    adddiuretic.diasbp_mean,
    adddiuretic.diasbp_min,
    adddiuretic.meanbp_max,
    adddiuretic.meanbp_mean,
    adddiuretic.meanbp_min,
    adddiuretic.resprate_max,
    adddiuretic.resprate_mean,
    adddiuretic.resprate_min,
    adddiuretic.spo2_max,
    adddiuretic.spo2_mean,
    adddiuretic.spo2_min,
    adddiuretic.urineoutput,
    adddiuretic.si_max,
    adddiuretic.si_mean,
    adddiuretic.si_min,
    adddiuretic.mingcs,
    adddiuretic.weight,
    adddiuretic.height,
    adddiuretic.saps,
    adddiuretic.sapsii,
    adddiuretic.sapsii_prob,
    adddiuretic.sofa,
    adddiuretic.sirs,
    adddiuretic.apsiii,
    adddiuretic.apsiii_prob,
    adddiuretic.oasis,
    adddiuretic.oasis_prob,
    adddiuretic.lods,
    adddiuretic.vent,
    adddiuretic.vaso,
    adddiuretic.diuretic,
        CASE
            WHEN (ad.hospital_expire_flag = 1) THEN 1
            ELSE 0
        END AS hospmor
   FROM (adddiuretic
     LEFT JOIN mimiciii.admissions ad ON (((ad.hadm_id = adddiuretic.hadm_id) AND (ad.subject_id = adddiuretic.subject_id))));
